apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mobile-mpc.fullname" . }}-ray-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mobile-mpc.labels" . | nindent 4 }}
data:
  gcs-port: "6379"  # 默认值，会被 Company 更新
  gcs-host: "{{ include "mobile-mpc.fullname" . }}-company-svc"

